wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.19.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746453701
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      3:
      - 4
      - 13
      - 16
      - 23
      - 42
      - 55
      4: 3.10.13
      5: 0.19.6
      8:
      - 5
      13: linux-x86_64
architecture:
  desc: null
  value: MLP_[200, 100, 100]
dropout:
  desc: null
  value: 0.2
dataset_train:
  desc: null
  value: train_5_200_100_500.txt
dataset_test:
  desc: null
  value: test_5_200_100_100.txt
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
schedulerType:
  desc: null
  value: StepLR
sched_step_size:
  desc: null
  value: 10
sched_gamma:
  desc: null
  value: 0.1
IMLE_n_samples:
  desc: null
  value: 10
IMLE_sigma:
  desc: null
  value: 1
IMLE_lambd:
  desc: null
  value: 10
IMLE_two_sides:
  desc: null
  value: false
IMLE_processes:
  desc: null
  value: 1
